### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException

### ISSUE THREAD

**Issue by Abgaryan** [roughike/flutter_facebook_login#110]
Crashlytics log from live app:

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean org.json.JSONObject.optBoolean(java.lang.String, boolean)' on a null object reference
       at com.facebook.UserSettingsManager$1.run(UserSettingsManager.java:148)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)
```

**Comment by ugoamanoh** [comment]
did you find a solution for this?

**Comment by Abgaryan** [comment]
> did you find a solution for this?
Suddenly I didn't.
