### ISSUE TITLE
App crashes on launch

### ISSUE THREAD

**Issue by johnlina** [roughike/flutter_facebook_login#115]
The app keeps crashing on launch with the follow exception message (already tried Flutter clean):

2019-04-12 22:40:52.845 14324-14324/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: br.com.tappsbeer.tapps_beer, PID: 14324
    java.lang.RuntimeException: Unable to start activity ComponentInfo{br.com.tappsbeer.tapps_beer/br.com.tappsbeer.tapps_beer.MainActivity}: The SDK has not been initialized, make sure to call FacebookSdk.sdkInitialize() first.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3113)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3249)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:81)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1940)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:209)
        at android.app.ActivityThread.main(ActivityThread.java:7046)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:486)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)
     Caused by: The SDK has not been initialized, make sure to call FacebookSdk.sdkInitialize() first.
        at com.facebook.internal.Validate.sdkInitialized(Validate.java:144)
        at com.facebook.login.LoginManager.<init>(LoginManager.java:80)
        at com.facebook.login.LoginManager.getInstance(LoginManager.java:93)
        at com.roughike.facebooklogin.facebooklogin.FacebookLoginPlugin$FacebookSignInDelegate.<init>(FacebookLoginPlugin.java:109)
        at com.roughike.facebooklogin.facebooklogin.FacebookLoginPlugin.<init>(FacebookLoginPlugin.java:38)
        at com.roughike.facebooklogin.facebooklogin.FacebookLoginPlugin.registerWith(FacebookLoginPlugin.java:42)
        at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:20)
        at br.com.tappsbeer.tapps_beer.MainActivity.onCreate(MainActivity.kt:11)
        at android.app.Activity.performCreate(Activity.java:7658)
        at android.app.Activity.performCreate(Activity.java:7647)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1295)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3088)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3249) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:81) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1940) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:209) 
        at android.app.ActivityThread.main(ActivityThread.java:7046)

**Comment by Aanu1995** [comment]
App crashes on launch in android

**Comment by heinzan** [comment]
same too

**Comment by heinzan** [comment]
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_webview_plugin: ^0.3.4
  url_launcher: ^4.0.2
  flutter_facebook_login: 1.2.0

This is my dependencies file.If i add facebook_login app is crash at launching.If don't add everything fine.Why?

**Comment by heinzan** [comment]
This solution was solved for me.We must configure as documentation of Android start to end.

**Comment by KishorTiwari** [comment]
@heinzan Can you put a link here? I am having issue with 1.20 version. App just crashes.

**Comment by Mayank1904** [comment]
Hi Heinzan how could you solve this problem , can you please elaborate?

**Comment by heinzan** [comment]
> Hi Heinzan how could you solve this problem , can you please elaborate?

Hi buddy,you must configure as documentation of Android start to end carefully.Please look documentation buddy.

**Comment by davydany** [comment]
This is the solution: https://github.com/roughike/flutter_facebook_login/issues/36
