### ISSUE TITLE
Android - App crashes on second startup. Clearing app data on device lets it run again.

### ISSUE THREAD

**Issue by Justin-Randall** [roughike/flutter_facebook_login#167]
Integrating flutter_facebook_login worked fine as per the instructions. The first time I debug the application, it starts and I can login via facebook with no problems. I see a user in Firebase and all works as expected.

I am targeting Android. This has been tested on multiple devices with the same behavior. One Samsung tablet, another Pixel 2.

When I attempt to start the application again, adb logs show the following exception (note [MY PROJECT] replaces the typical com.example.typical_flutter_project):

```
 FATAL EXCEPTION: main
 Process: [MY PROJECT], PID: 3098
 java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{[MY PROJECT]/[MY PROJECT].MainActivity}: java.lang.ClassNotFoundException: Didn't find class "[MY PROJECT].MainActivity" on path: DexPathList[[zip file "/data/app/[MY PROJECT]-JObNIJAMpmDPRJzmeAKfnw==/base.apk"],nativeLibraryDirectories=[/data/app/[MY PROJECT]-JObNIJAMpmDPRJzmeAKfnw==/lib/arm64, /data/app/[MY PROJECT]-JObNIJAMpmDPRJzmeAKfnw==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2846)
 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3037)
 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1701)
 	at android.os.Handler.dispatchMessage(Handler.java:105)
 	at android.os.Looper.loop(Looper.java:164)
 	at android.app.ActivityThread.main(ActivityThread.java:6949)
 	at java.lang.reflect.Method.invoke(Native Method)
 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
 Caused by: java.lang.ClassNotFoundException: Didn't find class "[MY PROJECT].MainActivity" on path: DexPathList[[zip file "/data/app/[MY PROJECT]-JObNIJAMpmDPRJzmeAKfnw==/base.apk"],nativeLibraryDirectories=[/data/app/[MY PROJECT]-JObNIJAMpmDPRJzmeAKfnw==/lib/arm64, /data/app/[MY PROJECT]-JObNIJAMpmDPRJzmeAKfnw==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
 	at android.app.Instrumentation.newActivity(Instrumentation.java:1180)
 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2836)
```

Removing the build directory and running flutter clean has no effect. The second startup will always fail with this error until I go into the device settings, find the application, then delete application data. Just deleting the cache will not work. I have to nuke the data.

There is something saved after the application is first run that prevents it starting properly the next time. I have scoured the project and tried to ensure the project name was the same everywhere. Is there some way to determine what is being saved on the device that could be causing this problem? It seems odd that it would run the first time with no problems, then completely face-plant at any attempt to start the application afterward.

**Comment by roughike** [comment]
Is this still a problem with version 3.0.0?

**Comment by baptisteArnaud** [comment]
I have an instant app crash as well whenever I include the package in pubspec. I use version 3.0.

Same problem if I include version 2.0

**Comment by DesortsSolution** [comment]
Same problem

**Comment by Justin-Randall** [comment]
> Is this still a problem with version 3.0.0?

Seems to be working with the latest version.
