### ISSUE TITLE
Facebook Platform - App has been restricted - Critical

### ISSUE THREAD

**Issue by ollydixon** [roughike/flutter_facebook_login#181]
Hello, I've had this message a few times now. It's fairly critical as now no one can login on Android. They are saying the Android version is using an old SDK. I'm only using this library to login.

Also is this the only Flutter Facebook library? Is anyone maintaining it?

```
Hi,

In working to create a great Platform experience for everyone, we ask developers to ensure the apps they build comply with our Platform Policies. Your app (-----) doesn't comply with the following Platform Policies:

Platform Policy 8.2: Native iOS and Android apps that implement Facebook Login must use our official SDKs for Login. 

Please make sure your Android app is using the most recent version of our SDK for Login. You can find more information on our Android SDK for Login and other Login-related products here: https://developers.facebook.com/docs/facebook-login/android.

You can see our visual example for this policy here: https://developers.facebook.com/policy#7-2-photo.


Since we're striving to improve the Platform experience, your app's ability to do the following has been restricted.
```

**Comment by alexei-g-aloteq** [comment]
Flutter is not a native app. Dumb Facebook bots...
I think you need to contact Facebook support somehow and let them know.

**Comment by ollydixon** [comment]
@alexei-g-aloteq it looks like the Flutter SDK is built on top of the native processes though. So it just needs to be updated on this plugin.

**Comment by alexei-g-aloteq** [comment]
Problem that the plugin does not include mentioned SDK and can not update nor keep it updated.

**Comment by alexei-g-aloteq** [comment]
But you are right - the plugin refers to old version of iOS SDK...

**Comment by ollydixon** [comment]
@alexei-g-aloteq this is related to Android...

**Comment by alexei-g-aloteq** [comment]
On Android you manually installing dependencies into gradle, so it should be updated automatically

**Comment by roughike** [comment]
The SDKs have been updated to latest versions in `flutter_facebook_login` 3.0.0. Does that fix the issue for you?

**Comment by ollydixon** [comment]
@roughike I'll rebuild and get back too you. (Need to push to both app stores). Thanks btw.

**Comment by ollydixon** [comment]
No luck. Bumping the verison breaks iOS.

```
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Finding Podfile changes
      - Flutter
      - camera
      - cloud_firestore
      - cloud_functions
      - firebase_analytics
      - firebase_auth
      - firebase_core
      - firebase_messaging
      - flutter_facebook_login
      - flutter_image_compress
      - flutter_is_emulator
      - image_cropper
      - image_picker
      - in_app_purchase
      - path_provider
      - shared_preferences
      - sqflite

    Fetching external sources
    -> Fetching podspec for `Flutter` from `.symlinks/flutter/ios-release`
    -> Fetching podspec for `camera` from `.symlinks/plugins/camera/ios`
    -> Fetching podspec for `cloud_firestore` from `.symlinks/plugins/cloud_firestore/ios`
    -> Fetching podspec for `cloud_functions` from `.symlinks/plugins/cloud_functions/ios`
    -> Fetching podspec for `firebase_analytics` from `.symlinks/plugins/firebase_analytics/ios`
    -> Fetching podspec for `firebase_auth` from `.symlinks/plugins/firebase_auth/ios`
    -> Fetching podspec for `firebase_core` from `.symlinks/plugins/firebase_core/ios`
    -> Fetching podspec for `firebase_messaging` from `.symlinks/plugins/firebase_messaging/ios`
    -> Fetching podspec for `flutter_facebook_login` from `.symlinks/plugins/flutter_facebook_login/ios`
    -> Fetching podspec for `flutter_image_compress` from `.symlinks/plugins/flutter_image_compress/ios`
    -> Fetching podspec for `flutter_is_emulator` from `.symlinks/plugins/flutter_is_emulator/ios`
    -> Fetching podspec for `image_cropper` from `.symlinks/plugins/image_cropper/ios`
    -> Fetching podspec for `image_picker` from `.symlinks/plugins/image_picker/ios`
    -> Fetching podspec for `in_app_purchase` from `.symlinks/plugins/in_app_purchase/ios`
    -> Fetching podspec for `path_provider` from `.symlinks/plugins/path_provider/ios`
    -> Fetching podspec for `shared_preferences` from `.symlinks/plugins/shared_preferences/ios`
    -> Fetching podspec for `sqflite` from `.symlinks/plugins/sqflite/ios`

    Resolving dependencies of `Podfile`
    [!] CocoaPods could not find compatible versions for pod "FBSDKLoginKit":
      In snapshot (Podfile.lock):
        FBSDKLoginKit (= 4.39.1)

      In Podfile:
        flutter_facebook_login (from `.symlinks/plugins/flutter_facebook_login/ios`) was resolved to 0.0.1, which depends on
          FBSDKLoginKit (~> 5.5)

    Specs satisfying the `FBSDKLoginKit (= 4.39.1), FBSDKLoginKit (~> 5.5)` dependency were found, but they required a higher minimum deployment target.

    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:328:in `raise_error_unless_state'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:310:in `block in unwind_for_conflict'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `tap'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `unwind_for_conflict'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:257:in `process_topmost_state'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:182:in `resolve'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/resolver.rb:88:in `resolve'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/installer/analyzer.rb:939:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/installer/analyzer.rb:937:in `resolve_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/installer/analyzer.rb:118:in `analyze'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:398:in `analyze'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:221:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:220:in `resolve_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:156:in `install!'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/command/install.rb:51:in `run'
    /Library/Ruby/Gems/2.3.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.5/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:22:in `load'
    /usr/local/bin/pod:22:in `<main>'

Error output from CocoaPods:
↳

    [!] Automatically assigning platform `ios` with version `10.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See
    `https://guides.cocoapods.org/syntax/podfile.html#platform`.

Error running pod install
```

**Comment by roughike** [comment]
You could try deleting `<your project>/ios/Podfile.lock` and then running `pod repo update && pod install` in the same ios folder.

**Comment by ollydixon** [comment]
@roughike same error. Just FYI Flutter does that automatically when you update packages and rebuild.

**Comment by w4-sglim** [comment]
I've also experienced the similar issue.

`Specs satisfying the `FBSDKLoginKit (= 4.39.1), FBSDKLoginKit (~> 5.5)` dependency were found, but they required a higher minimum deployment target.
`
 After I tried to run `pod repo update && pod install` I got another error.

```
[!] CocoaPods could not find compatible versions for pod "flutter_facebook_login":
  In Podfile:
    flutter_facebook_login (from `.symlinks/plugins/flutter_facebook_login/ios`)

Specs satisfying the `flutter_facebook_login (from `.symlinks/plugins/flutter_facebook_login/ios`)` dependency were found, but they required a higher minimum deployment target.
```

**Comment by roughike** [comment]
@ollydixon & @w4-sglim: To be clear, did you:
1. first delete `<your project>/ios/Podfile.lock`
2. then try to run the project?

If you skip step number 1, you'll encounter the issue. At least for me and my coworkers, the issue resolves by deleting `<your project>/ios/Podfile.lock` and then running.

**Comment by sglim** [comment]
Actually, I already tried to delete the ‘Podfile.lock’ but it is the same as before. And I tried the following:
* remove Pods folder
* flutter clean

**Comment by ollydixon** [comment]
@roughike it's the first time I've had to do this for any Flutter project for a package (9+ in counting now).

(Project directory)
`rm -rf Pods`
Tried: `pod install`
Tried just **running the project**

Noting works, the library is broken. Going back to 2.0.0 works. :-/

Thank you for helping.

**Comment by roughike** [comment]
@ollydixon & @sglim could you attach the output of `flutter doctor` here? I'm on Catalina (had to upgrade to push an iOS 13 related release out), so it might be that our setup is different.

**Comment by sroddy** [comment]
As it's written in the error message, you need to set a higher minimum deployment target.

In you Podfile just uncomment and fix  this line:

```
# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
```

**Comment by simformsolutions** [comment]
# platform :ios, '9.0'

Try uncommenting this line.
It resolved the issue.

**Comment by ollydixon** [comment]
@sroddy I don't have this in the PodFile but it's still failing.

**Comment by sroddy** [comment]
@ollydixon you need that line, and you need it to specify at least version `9.0`, otherwise it will fail.

On top of that, please make sure to also have run `pod update` at least once before running `pod install`

**Comment by w4-sglim** [comment]
After uncommenting the line for minimun platform version, remove Podfile.lock, I success to run `pod install` finally!
Thank you for your helping @sroddy .

**Comment by ollydixon** [comment]
Thanks @sroddy but we shouldn't really be speifying these things, they are handled by the Flutter packages usually.

Anyhow, after doing that I have some new error that is related to Facebook once again.

```
Xcode's output:
↳
    /Users/olly/Projects/instagram/ios/Pods/FMDB/src/fmdb/FMDatabase.m:1486:15: warning: 'sqlite3_wal_checkpoint_v2' is only available on iOS 5.0 or newer [-Wunguarded-availability]
        int err = sqlite3_wal_checkpoint_v2(_db, dbName, checkpointMode, logFrameCount, checkpointCount);
                  ^~~~~~~~~~~~~~~~~~~~~~~~~
    In module 'SQLite3' imported from /Users/olly/Projects/instagram/ios/Pods/FMDB/src/fmdb/FMDatabase.m:8:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.0.sdk/usr/include/sqlite3.h:8428:16: note: 'sqlite3_wal_checkpoint_v2' has been marked as being introduced in iOS 5.0 here, but the deployment target is iOS 4.3.0
    SQLITE_API int sqlite3_wal_checkpoint_v2(
                   ^
    /Users/olly/Projects/instagram/ios/Pods/FMDB/src/fmdb/FMDatabase.m:1486:15: note: enclose 'sqlite3_wal_checkpoint_v2' in an @available check to silence this warning
        int err = sqlite3_wal_checkpoint_v2(_db, dbName, checkpointMode, logFrameCount, checkpointCount);
                  ^~~~~~~~~~~~~~~~~~~~~~~~~
    1 warning generated.
    /Users/olly/Projects/instagram/ios/Pods/FMDB/src/fmdb/FMDatabaseQueue.m:101:9: warning: 'dispatch_queue_set_specific' is only available on iOS 5.0 or newer [-Wunguarded-availability]
            dispatch_queue_set_specific(_queue, kDispatchQueueSpecificKey, (__bridge void *)self, NULL);
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~
    In module 'Foundation' imported from /Users/olly/Projects/instagram/ios/Pods/FMDB/src/fmdb/FMDatabaseQueue.h:9:
    In module 'CoreFoundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.0.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:
    In module 'Dispatch' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.0.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFStream.h:20:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.0.sdk/usr/include/dispatch/queue.h:1498:1: note: 'dispatch_queue_set_specific' has been marked as being introduced in iOS 5.0 here, but the deployment target is iOS 4.3.0
    dispatch_queue_set_specific(dispatch_queue_t queue, const void *key,
```

**Comment by sroddy** [comment]
@roughike It may be worth to add a line or two inside the readme to explain this.

**Comment by ollydixon** [comment]
I deleted all my derived data,

Running

```
flutter clean
rm -rf ~/Library/Caches/CocoaPods
rm -rf ios/Pods
pod update
```

Remove the lock files etc.

I tried recreating the project. Running Xcode 11 with 10.14.6 (Mojava). Same errors.

Still get lots of build errors. Not happening when I remove the plugin :-/

**Comment by roughike** [comment]
@sroddy What's the reason for needing 9.0 to be the minimum deployment target for this plugin? 

I saw on #169 that it was bumped from 8.0 to 9.0 and thought it's because of some of the dictionary keys being only available on iOS 9.0. However, it seems that all of the official Flutter plugins always use 8.0 - the iOS plugin template is also set to 8.0.

I'm just thinking if the issue is that all other Flutter projects & the tooling are using 8.0 as the minimum. If so, it might be a little painful for users to update to 9.0 just to use a simple Facebook login SDK and we might want to revert the minimum deployment target back to 8.0.

**Comment by ollydixon** [comment]
@roughike well the good news is Android SDK is working great.

The bad news is that with Xcode 11 Flutter release for iOS don't build :-|

**Comment by OliverNarramore** [comment]
I am facing the same issue. I am using 3.0.0 and the login user faces an error "Application Unavailable: The application you're trying to use is either no longer available or access is restricted."

Any advice? Thank you

**Comment by ollydixon** [comment]
@OliverNarramore you need to repeal with Facebook, use developer.facebook.com to do this.

**Comment by sroddy** [comment]
@roughike It was probably something that I did without too much reasoning. It might be (but I might also be very wrong here) that when updating the code I've seen that there were issues related to unavailable APIs in previous SDKs that was making the code of this plugin unusable.

But I honestly can't remember... can you please give it a try, and see if rolling back that number doesn't cause any major issue?

Thanks and sorry again for the issue
