### ISSUE TITLE
android click facebook login

### ISSUE THREAD

**Issue by armygui** [roughike/flutter_facebook_login#259]
Click facebook login in android, then cancel, close the application, enter again, click again and then cancel, an exception occurs
error message： Caused by: java.lang.IllegalStateException: Reply already submitted
	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:4)
 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:1)
 	at com.roughike.facebooklogin.facebooklogin.b.a(FacebookLoginResultDelegate.java:8)
	at com.roughike.facebooklogin.facebooklogin.b.a(FacebookLoginResultDelegate.java:5)
 	at com.facebook.login.g.a(LoginManager.java:75)
	at com.facebook.login.g.a(LoginManager.java:18)
 	at com.facebook.login.g$a.a(LoginManager.java:1)

**Comment by talhakhan011** [comment]
facing same issue resolve it please
