### ISSUE TITLE
Conflict with geolocator 

### ISSUE THREAD

**Issue by zeeshan1010** [roughike/flutter_facebook_login#287]
E/flutter (30690): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: MissingPluginException(No implementation found for method checkPermissionStatus on channel com.baseflow.flutter/location_permissions)
E/flutter (30690): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:7)
E/flutter (30690): <asynchronous suspension>
E/flutter (30690): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:334:12)
E/flutter (30690): #2      LocationPermissions.checkPermissionStatus (package:location_permissions/src/location_permissions.dart:38:30)
E/flutter (30690): #3      Geolocator._getLocationPermission (package:zemaasdine/geolocator/geolocator.dart:201:10)
E/flutter (30690): #4      Geolocator.getCurrentPosition (package:zemaasdine/geolocator/geolocator.dart:101:47)
E/flutter (30690): #5      _SplashScreenState._getCurrentLocation (package:zemaasdine/screens/splashScreen.dart:85:35)
E/flutter (30690): #6      _SplashScreenState._checkInternetAvailability (package:zemaasdine/screens/splashScreen.dart:62:7)
E/flutter (30690): <asynchronous suspension>
E/flutter (30690): #7      _SplashScreenState.initState (package:zemaasdine/screens/splashScreen.dart:115:5)
E/flutter (30690): #8      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4684:58)
E/flutter (30690): #9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
E/flutter (30690): #10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
E/flutter (30690): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
E/flutter (30690): #12     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5874:14)
E/flutter (30690): #13     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
E/flutter (30690): #14     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
E/flutter (30690): #15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
E/flutter (30690): #16     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
E/flutter (30690): #17     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
E/flutter (30690): #18     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
E/flutter (30690): #19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
E/flutter (30690): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
E/flutter (30690): #21     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5874:14)
E/flutter (30690): #22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
E/flutter (30690): #23     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
E/flutter (30690): #24     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5874:14)
E/flutter (30690): #25     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
E/flutter (30690): #26     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
E/flutter (30690): #27     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
E/flutter (30690): #28     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
E/flutter (30690): #29     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
E/flutter (30690): #30     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
E/flutter (30690): #31     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4710:11)
E/flutter (30690): #32     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
E/flutter (30690): #33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
E/flutter (30690): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
E/flutter (30690): #35     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5874:14)
E/flutter (30690): #36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
E/flutter (30690): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
E/flutter (30690): #38     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5874:14)
E/flutter (30690): #39     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
E/flutter (30690): #40     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
E/flutter (30690): #41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
E/flutter (30690): #42     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:

**Comment by rogiervandenberg** [comment]
You need to set all the settings for Facebook correctly (i.e. `android/app/src/main/res/values/strings.xml` and `android/app/src/main/AndroidManifest.xml` stuff). If you do so, it will work again.

If by the way geolocator is not working because of 'hanging', do add `<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />` to your AndroidManifest.xml.
