### ISSUE TITLE
Login with facebook on Android side Crashing if there is no Facebook app

### ISSUE THREAD

**Issue by m-amin** [roughike/flutter_facebook_login#298]
I am using flutter_facebook_login 3.0.0 version. There is an issue with login_with_facebook does not working on Android. I think the reason is if you do not have faceboook app on the device the login_with_facebook crashing but I am not sure. Does anyone has this issue ?

```
W/ActivityThread( 3835): handleWindowVisibility: no activity for token android.os.BinderProxy@d2a7401
D/AndroidRuntime( 3835): Shutting down VM
E/AndroidRuntime( 3835): FATAL EXCEPTION: main
E/AndroidRuntime( 3835): Process: com.asd.android, PID: 3835
E/AndroidRuntime( 3835): java.lang.NoSuchMethodError: No static method createProxyAuthIntent(Landroid/content/Context;Ljava/lang/String;Ljava/util/Collection;Ljava/lang/String;ZZLcom/facebook/login/DefaultAudience;Ljava/lang/String;Ljava/lang/String;)Landroid/content/Intent; in class Lcom/facebook/internal/NativeProtocol; or its super classes (declaration of 'com.facebook.internal.NativeProtocol' appears in /data/app/com.asd.android-yFArFXU1ndqk1qS4cpm6sA==/base.apk)
E/AndroidRuntime( 3835):    at com.facebook.login.KatanaProxyLoginMethodHandler.tryAuthorize(KatanaProxyLoginMethodHandler.java:44)
E/AndroidRuntime( 3835):    at com.facebook.login.LoginClient.tryCurrentHandler(LoginClient.java:264)
E/AndroidRuntime( 3835):    at com.facebook.login.LoginClient.tryNextHandler(LoginClient.java:216)
E/AndroidRuntime( 3835):    at com.facebook.login.LoginClient.authorize(LoginClient.java:121)
E/AndroidRuntime( 3835):    at com.facebook.login.LoginClient.startOrContinueAuth(LoginClient.java:102)
E/AndroidRuntime( 3835):    at com.facebook.login.LoginFragment.onResume(LoginFragment.java:160)
E/AndroidRuntime( 3835):    at androidx.fragment.app.Fragment.performResume(Fragment.java:2649)
E/AndroidRuntime( 3835):    at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:922)
E/AndroidRuntime( 3835):    at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
E/AndroidRuntime( 3835):    at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
E/AndroidRuntime( 3835):    at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2659)
E/AndroidRuntime( 3835):    at androidx.fragment.app.FragmentManagerImpl.dispatchResume(FragmentManagerImpl.java:2625)
E/AndroidRuntime( 3835):    at androidx.fragment.app.FragmentController.dispatchResume(FragmentController.java:268)
E/AndroidRuntime( 3835):    at androidx.fragment.app.FragmentActivity.onResumeFragments(FragmentActivity.java:479)
E/AndroidRuntime( 3835):    at androidx.fragment.app.FragmentActivity.onPostResume(FragmentActivity.java:468)
E/AndroidRuntime( 3835):    at android.app.Activity.performResume(Activity.java:7317)
E/AndroidRuntime( 3835):    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3776)
E/AndroidRuntime( 3835):    at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3816)
E/AndroidRuntime( 3835):    at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
E/AndroidRuntime( 3835):    at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
E/AndroidRuntime( 3835):    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
E/AndroidRuntime( 3835):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
E/AndroidRuntime( 3835):    at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 3835):    at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime( 3835):    at android.app.ActivityThread.main(ActivityThread.java:6669)
E/AndroidRuntime( 3835):    at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 3835):    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime( 3835):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/CrashlyticsCore( 3835): Can't find SessionUser data for session ID 5FB67E1B0149-0001-7208-82D4D8267C33
I/Process ( 3835): Sending signal. PID: 3835 SIG: 9
```

**Comment by aminhotob** [comment]
I have facebook app and have the same error


E/AndroidRuntime( 7171): FATAL EXCEPTION: main
E/AndroidRuntime( 7171): Process: com.xxx, PID: 7171
E/AndroidRuntime( 7171): java.lang.NoSuchMethodError: No static method createProxyAuthIntent(Landroid/content/Context;Ljava/lang/String;Ljava/util/Collection;Ljava/lang/String;ZZLcom/facebook/login/DefaultAudience;Ljava/lang/String;Ljava/lang/String;)Landroid/content/Intent; in class Lcom/facebook/internal/NativeProtocol; or its super classes (declaration of 'com.facebook.internal.NativeProtocol' appears in /data/app/com.xxx/base.apk)
E/AndroidRuntime( 7171):        at com.facebook.login.KatanaProxyLoginMethodHandler.tryAuthorize(KatanaProxyLoginMethodHandler.java:44)
E/AndroidRuntime( 7171):        at com.facebook.login.LoginClient.tryCurrentHandler(LoginClient.java:264)
E/AndroidRuntime( 7171):        at com.facebook.login.LoginClient.tryNextHandler(LoginClient.java:216)
E/AndroidRuntime( 7171):        at com.facebook.login.GetTokenLoginMethodHandler.getTokenCompleted(GetTokenLoginMethodHandler.java:119)
E/AndroidRuntime( 7171):        at com.facebook.login.GetTokenLoginMethodHandler$1.completed(GetTokenLoginMethodHandler.java:74)
E/AndroidRuntime( 7171):        at com.facebook.internal.PlatformServiceClient.callback(PlatformServiceClient.java:163)
E/AndroidRuntime( 7171):        at com.facebook.internal.PlatformServiceClient.handleMessage(PlatformServiceClient.java:143)
E/AndroidRuntime( 7171):        at com.facebook.internal.PlatformServiceClient$1.handleMessage(PlatformServiceClient.java:64)
E/AndroidRuntime( 7171):        at android.os.Handler.dispatchMessage(Handler.java:111)
E/AndroidRuntime( 7171):        at android.os.Looper.loop(Looper.java:194)
E/AndroidRuntime( 7171):        at android.app.ActivityThread.main(ActivityThread.java:5637)
E/AndroidRuntime( 7171):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 7171):        at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 7171):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
E/AndroidRuntime( 7171):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)
E/WifiTrafficPoller(30763): TRAFFIC_STATS_POLL true Token 33 num clients 8
E/WifiTrafficPoller(30763):  packet count Tx=53516 Rx=66967
E/GED     (31355): Failed to get GED Log Buf, err(0)
E/JavaBinder(30763): *** Uncaught remote exception!  (Exceptions are not yet supported across processes.)
E/JavaBinder(30763): java.lang.ArrayIndexOutOfBoundsException: length=5; index=5
E/JavaBinder(30763):    at com.android.internal.os.BatteryStatsImpl.updateAllPhoneStateLocked(BatteryStatsImpl.java:3321)
E/JavaBinder(30763):    at com.android.internal.os.BatteryStatsImpl.notePhoneSignalStrengthLocked(BatteryStatsImpl.java:3351)
E/JavaBinder(30763):    at com.android.server.am.BatteryStatsService.notePhoneSignalStrength(BatteryStatsService.java:395)
E/JavaBinder(30763):    at com.android.server.TelephonyRegistry.broadcastSignalStrengthChanged(TelephonyRegistry.java:1484)
E/JavaBinder(30763):    at com.android.server.TelephonyRegistry.notifySignalStrengthForSubscriber(TelephonyRegistry.java:873)
E/JavaBinder(30763):    at com.android.internal.telephony.ITelephonyRegistry$Stub.onTransact(ITelephonyRegistry.java:184)
E/JavaBinder(30763):    at android.os.Binder.execTransact(Binder.java:451)
E/JavaBinder(30763): *** Uncaught remote exception!  (Exceptions are not yet supported across processes.)
E/JavaBinder(30763): java.lang.ArrayIndexOutOfBoundsException: length=5; index=5
E/JavaBinder(30763):    at com.android.internal.os.BatteryStatsImpl.updateAllPhoneStateLocked(BatteryStatsImpl.java:3321)
E/JavaBinder(30763):    at com.android.internal.os.BatteryStatsImpl.notePhoneStateLocked(BatteryStatsImpl.java:3345)
E/JavaBinder(30763):    at com.android.server.am.BatteryStatsService.notePhoneState(BatteryStatsService.java:410)
E/JavaBinder(30763):    at com.android.server.TelephonyRegistry.broadcastServiceStateChanged(TelephonyRegistry.java:1461)
E/JavaBinder(30763):    at com.android.server.TelephonyRegistry.notifyServiceStateForPhoneId(TelephonyRegistry.java:811)
E/JavaBinder(30763):    at com.android.internal.telephony.ITelephonyRegistry$Stub.onTransact(ITelephonyRegistry.java:154)
E/JavaBinder(30763):    at android.os.Binder.execTransact(Binder.java:451)

**Comment by aminhotob** [comment]
I have facebook app and have the same error

E/AndroidRuntime( 7171): FATAL EXCEPTION: main
E/AndroidRuntime( 7171): Process: com.xxx, PID: 7171
E/AndroidRuntime( 7171): java.lang.NoSuchMethodError: No static method createProxyAuthIntent(Landroid/content/Context;Ljava/lang/String;Ljava/util/Collection;Ljava/lang/String;ZZLcom/facebook/login/DefaultAudience;Ljava/lang/String;Ljava/lang/String;)Landroid/content/Intent; in class Lcom/facebook/internal/NativeProtocol; or its super classes (declaration of 'com.facebook.internal.NativeProtocol' appears in /data/app/com.xxx/base.apk)
E/AndroidRuntime( 7171): at com.facebook.login.KatanaProxyLoginMethodHandler.tryAuthorize(KatanaProxyLoginMethodHandler.java:44)
E/AndroidRuntime( 7171): at com.facebook.login.LoginClient.tryCurrentHandler(LoginClient.java:264)
E/AndroidRuntime( 7171): at com.facebook.login.LoginClient.tryNextHandler(LoginClient.java:216)
E/AndroidRuntime( 7171): at com.facebook.login.GetTokenLoginMethodHandler.getTokenCompleted(GetTokenLoginMethodHandler.java:119)
E/AndroidRuntime( 7171): at com.facebook.login.GetTokenLoginMethodHandler$1.completed(GetTokenLoginMethodHandler.java:74)
E/AndroidRuntime( 7171): at com.facebook.internal.PlatformServiceClient.callback(PlatformServiceClient.java:163)
E/AndroidRuntime( 7171): at com.facebook.internal.PlatformServiceClient.handleMessage(PlatformServiceClient.java:143)
E/AndroidRuntime( 7171): at com.facebook.internal.PlatformServiceClient$1.handleMessage(PlatformServiceClient.java:64)
E/AndroidRuntime( 7171): at android.os.Handler.dispatchMessage(Handler.java:111)
E/AndroidRuntime( 7171): at android.os.Looper.loop(Looper.java:194)
E/AndroidRuntime( 7171): at android.app.ActivityThread.main(ActivityThread.java:5637)
E/AndroidRuntime( 7171): at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 7171): at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 7171): at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
E/AndroidRuntime( 7171): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)

**Comment by daniilsv** [comment]
still have same problem

**Comment by vipindhangar1107** [comment]
Having the same issue

**Comment by mhassanist** [comment]
Same issue here.
