### ISSUE TITLE
Android Release Build CRASH

### ISSUE THREAD

**Issue by danielgchap** [roughike/flutter_facebook_login#301]
- flutter run --release
- app crashes with following output:
```
[        ] Installing build/app/outputs/flutter-apk/app.apk... (completed in 6.0s)
[        ] executing: /Users/danielchapman/Library/Android/sdk/platform-tools/adb -s ZY323HWSM7 shell echo -n
6f62cec15517ccbd0deac4036c845c5a731c6833 > /data/local/tmp/sky.com.PrayerPal.sha1
[  +40 ms] executing: /Users/danielchapman/Library/Android/sdk/platform-tools/adb -s ZY323HWSM7 shell am start -a android.intent.action.RUN -f
0x20000000 --ez enable-background-compilation true --ez enable-dart-profiling true com.PrayerPal/com.PrayerPal.MainActivity
[ +151 ms] Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.PrayerPal/.MainActivity (has extras) }
[   +5 ms] Application running.
[   +2 ms] Flutter run key commands.
[   +2 ms] h Repeat this help message.
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[ +558 ms] E/AndroidRuntime(14686): FATAL EXCEPTION: AsyncTask #1
[        ] E/AndroidRuntime(14686): Process: com.PrayerPal, PID: 14686
[        ] E/AndroidRuntime(14686): java.lang.ExceptionInInitializerError
[        ] E/AndroidRuntime(14686):     at com.facebook.internal.k0.e(Unknown Source:0)
[        ] E/AndroidRuntime(14686):     at com.facebook.internal.S.k(Unknown Source:102)
[        ] E/AndroidRuntime(14686):     at com.facebook.internal.S.m(Unknown Source:27)
[        ] E/AndroidRuntime(14686):     at com.facebook.p0.run(Unknown Source:15)
[        ] E/AndroidRuntime(14686):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
[        ] E/AndroidRuntime(14686):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
[        ] E/AndroidRuntime(14686):     at java.lang.Thread.run(Thread.java:919)
[        ] E/AndroidRuntime(14686): Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: com.facebook.internal.k0.values []
[        ] E/AndroidRuntime(14686):     at java.lang.Enum.enumValues(Enum.java:270)
[        ] E/AndroidRuntime(14686):     at java.lang.Enum.access$000(Enum.java:61)
[        ] E/AndroidRuntime(14686):     at java.lang.Enum$1.create(Enum.java:277)
[        ] E/AndroidRuntime(14686):     at java.lang.Enum$1.create(Enum.java:275)
[        ] E/AndroidRuntime(14686):     at libcore.util.BasicLruCache.get(BasicLruCache.java:63)
[        ] E/AndroidRuntime(14686):     at java.lang.Enum.getSharedConstants(Enum.java:289)
[        ] E/AndroidRuntime(14686):     at java.lang.Class.getEnumConstantsShared(Class.java:2428)
[        ] E/AndroidRuntime(14686):     at java.util.EnumSet.getUniverse(EnumSet.java:407)
[        ] E/AndroidRuntime(14686):     at java.util.EnumSet.noneOf(EnumSet.java:109)
[        ] E/AndroidRuntime(14686):     at java.util.EnumSet.allOf(EnumSet.java:130)
[        ] E/AndroidRuntime(14686):     at com.facebook.internal.k0.<clinit>(Unknown Source:38)
[        ] E/AndroidRuntime(14686):     ... 7 more
[        ] E/AndroidRuntime(14686): Caused by: java.lang.NoSuchMethodException: com.facebook.internal.k0.values []
[        ] E/AndroidRuntime(14686):     at java.lang.Class.getMethod(Class.java:2072)
[        ] E/AndroidRuntime(14686):     at java.lang.Class.getDeclaredMethod(Class.java:2050)
[        ] E/AndroidRuntime(14686):     at java.lang.Enum.enumValues(Enum.java:267)
[        ] E/AndroidRuntime(14686):     ... 17 more

```

Flutter doctor:
```
[✓] Flutter (Channel master, 1.25.0-9.0.pre.88, on Mac OS X 10.15.7 19H15 darwin-x64, locale en-US)
    • Flutter version 1.25.0-9.0.pre.88 at /Users/danielchapman/Dev/flutter
    • Framework revision e24e763872 (6 hours ago), 2020-12-16 07:33:03 -0500
    • Engine revision e9f2f0eaea
    • Dart version 2.12.0 (build 2.12.0-157.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/danielchapman/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.17.0

[✓] Connected device (2 available)
    • motorola one (mobile) • ZY323HWSM7 • android-arm64  • Android 10 (API 29)
    • Chrome (web)          • chrome     • web-javascript • Google Chrome 87.0.4280.88

• No issues found!
```

**Comment by danielgchap** [comment]
Thank you!

**Comment by darwin-morocho** [comment]
> Thank you!

This plugin has not more support maybe you need change the plugin with flutter_facebook_auth
