### ISSUE TITLE
App crash when running release

### ISSUE THREAD

**Issue by viirak** [roughike/flutter_facebook_login#327]
E/AndroidRuntime(23518): java.lang.ExceptionInInitializerError
[        ] E/AndroidRuntime(23518):     at com.facebook.internal.k0.b(Unknown Source:0)
[        ] E/AndroidRuntime(23518):     at com.facebook.internal.S.k(Unknown Source:102)
[        ] E/AndroidRuntime(23518):     at com.facebook.internal.S.m(Unknown Source:27)
[        ] E/AndroidRuntime(23518):     at com.facebook.p0.run(Unknown Source:15)
[        ] E/AndroidRuntime(23518):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
[        ] E/AndroidRuntime(23518):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
[        ] E/AndroidRuntime(23518):     at java.lang.Thread.run(Thread.java:919)
[        ] E/AndroidRuntime(23518): Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: com.facebook.internal.k0.values []
[        ] E/AndroidRuntime(23518):     at java.lang.Enum.enumValues(Enum.java:270)
[        ] E/AndroidRuntime(23518):     at java.lang.Enum.access$000(Enum.java:61)
[        ] E/AndroidRuntime(23518):     at java.lang.Enum$1.create(Enum.java:277)
[        ] E/AndroidRuntime(23518):     at java.lang.Enum$1.create(Enum.java:275)
[        ] E/AndroidRuntime(23518):     at libcore.util.BasicLruCache.get(BasicLruCache.java:63)
[        ] E/AndroidRuntime(23518):     at java.lang.Enum.getSharedConstants(Enum.java:289)
[        ] E/AndroidRuntime(23518):     at java.lang.Class.getEnumConstantsShared(Class.java:2428)
[        ] E/AndroidRuntime(23518):     at java.util.EnumSet.getUniverse(EnumSet.java:407)
[        ] E/AndroidRuntime(23518):     at java.util.EnumSet.noneOf(EnumSet.java:109)
[        ] E/AndroidRuntime(23518):     at java.util.EnumSet.allOf(EnumSet.java:130)
[        ] E/AndroidRuntime(23518):     at com.facebook.internal.k0.<clinit>(Unknown Source:38)
[        ] E/AndroidRuntime(23518):     ... 7 more
[        ] E/AndroidRuntime(23518): Caused by: java.lang.NoSuchMethodException: com.facebook.internal.k0.values []
[        ] E/AndroidRuntime(23518):     at java.lang.Class.getMethod(Class.java:2072)
[        ] E/AndroidRuntime(23518):     at java.lang.Class.getDeclaredMethod(Class.java:2050)
[        ] E/AndroidRuntime(23518):     at java.lang.Enum.enumValues(Enum.java:267)
[        ] E/AndroidRuntime(23518):     ... 17 more

**Comment by viirak** [comment]
it seems like adding implementation facebook-login:9.0.0 to app/build.gradle fixes the issue.

implementation 'com.facebook.android:facebook-login:9.0.0'
