### ISSUE TITLE
Exception, when trying to run the example from the README

### ISSUE THREAD

**Issue by d-silveira** [roughike/flutter_facebook_login#34]
Hi @roughike, thanks for writing this lib, I had a major issue though...

**I got this exception, when trying to run the example from the README:**
```
E/flutter (31936): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (31936): MissingPluginException(No implementation found for method loginWithReadPermissions on channel com.roughike/flutter_facebook_login)
E/flutter (31936): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:278:7)
E/flutter (31936): <asynchronous suspension>
E/flutter (31936): #1      FacebookLogin.logInWithReadPermissions (package:flutter_facebook_login/flutter_facebook_login.dart:101:23)
E/flutter (31936): <asynchronous suspension>
E/flutter (31936): #2      LoginSelectPageState.loginWithFacebook (package:project/login/login_select_page.dart:61:41)
```
**Flutter doctor:**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.5.1, on Linux, locale en_GB.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[✓] Android Studio (version 3.1)
[✓] Connected devices (1 available)

• No issues found!
flutter doctor  13.61s user 1.22s system 185% cpu 8.014 total
```

**Comment by d-silveira** [comment]
it turns out a full rebuild was needed, problem solved, thanks!
