### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException

### ISSUE THREAD

**Issue by lizhuoyuan** [roughike/flutter_facebook_login#86]
Fatal Exception: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=64206, result=-1, data=Intent { (has extras) }} to activity {com.cari.promo.diskon/com.cari.promo.diskon.MainActivity}: java.lang.IllegalStateException: Reply already submitted
       at android.app.ActivityThread.deliverResults(ActivityThread.java:3714)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:3757)
       at android.app.ActivityThread.-wrap16(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1394)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5452)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:762)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:652)

**Comment by lizhuoyuan** [comment]
Caused by java.lang.IllegalStateException: Reply already submitted
       at io.flutter.view.FlutterNativeView$1.reply(Unknown Source)
       at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(Unknown Source)
       at com.roughike.facebooklogin.facebooklogin.FacebookLoginResultDelegate.finishWithResult(Unknown Source)
       at com.roughike.facebooklogin.facebooklogin.FacebookLoginResultDelegate.onSuccess(Unknown Source)
       at com.roughike.facebooklogin.facebooklogin.FacebookLoginResultDelegate.onSuccess(Unknown Source)
       at com.facebook.login.LoginManager.finishLogin(Unknown Source)
       at com.facebook.login.LoginManager.onActivityResult(Unknown Source)
       at com.facebook.login.LoginManager$1.onActivityResult(Unknown Source)
       at com.facebook.internal.CallbackManagerImpl.onActivityResult(Unknown Source)
       at com.roughike.facebooklogin.facebooklogin.FacebookLoginResultDelegate.onActivityResult(Unknown Source)
       at io.flutter.app.FlutterPluginRegistry.onActivityResult(Unknown Source)
       at io.flutter.app.FlutterActivityDelegate.onActivityResult(Unknown Source)
       at io.flutter.app.FlutterActivity.onActivityResult(Unknown Source)
       at com.cari.promo.diskon.MainActivity.onActivityResult(Unknown Source)
       at android.app.Activity.dispatchActivityResult(Activity.java:6456)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:3710)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:3757)
       at android.app.ActivityThread.-wrap16(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1394)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5452)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:762)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:652)


how to fix it 
![image](https://user-images.githubusercontent.com/15923901/51880850-c30c6b80-23b3-11e9-9024-6689837d6842.png)

**Comment by Froelund** [comment]
We just encountered the same issue. @lizhuoyuan did you find a solution?

**Comment by lizhuoyuan** [comment]
If I remember correctly, it should be the problem of flutter itself.

**Comment by sanjeevbaria** [comment]
any solution?
