### ISSUE TITLE
App Crashes On launch with The SDK has not been initialized, make sure to call FacebookSdk.sdkInitialize() first

### ISSUE THREAD

**Issue by kotlincodes** [roughike/flutter_facebook_login#99]
I am trying to integrate facebook login with Flutter using the instructions provided here for android.

I think it is a official plugin , I have followed everything in this documentation but I am getting the following error and app crashes on Launch.

Error Log

`java.lang.RuntimeException: Unable to start activity ComponentInfo{com.shrishtionline.quikpayagent/com.shrishtionline.quikpayagent.MainActivity}: The SDK has not been initialized, make sure to call FacebookSdk.sdkInitialize() first.
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2724)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2789)
    at android.app.ActivityThread.-wrap12(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1527)
    at android.os.Handler.dispatchMessage(Handler.java:110)
    at android.os.Looper.loop(Looper.java:203)
    at android.app.ActivityThread.main(ActivityThread.java:6251)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1075)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
 Caused by: The SDK has not been initialized, make sure to call FacebookSdk.sdkInitialize() first.
    at com.facebook.internal.Validate.sdkInitialized(Validate.java:143)
    at com.facebook.login.LoginManager.<init>(LoginManager.java:79)
    at com.facebook.login.LoginManager.getInstance(LoginManager.java:92)
    at com.roughike.facebooklogin.facebooklogin.FacebookLoginPlugin$FacebookSignInDelegate.<init>(FacebookLoginPlugin.java:109)
    at com.roughike.facebooklogin.facebooklogin.FacebookLoginPlugin.<init>(FacebookLoginPlugin.java:38)
    at com.roughike.facebooklogin.facebooklogin.FacebookLoginPlugin.registerWith(FacebookLoginPlugin.java:42)
    at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:23)
    at com.shrishtionline.quikpayagent.MainActivity.onCreate(MainActivity.java:11)
    at android.app.Activity.performCreate(Activity.java:6666)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2677)`

The error log says to call `FacebookSdk.sdkInitialize()` , But in dart I am not able to call this code. But I have initialized Facebook SDK with `static final FacebookLogin facebookSignIn = new FacebookLogin();` method.

I have browsed a lot but I am not able to solve out this issue.

I am Using the latest version of the plugin.

**Comment by kotlincodes** [comment]
Issue will be solved with flutter clean

**Comment by function1983** [comment]
Flutter clean doesn't work for me. I hope the error message from this plugin and facebook could had been more detailed for troubleshooting purposes.

**Comment by johnlina** [comment]
Facing this error right now:

2019-04-12 22:40:52.845 14324-14324/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: br.com.tappsbeer.tapps_beer, PID: 14324
    java.lang.RuntimeException: Unable to start activity ComponentInfo{br.com.tappsbeer.tapps_beer/br.com.tappsbeer.tapps_beer.MainActivity}: The SDK has not been initialized, make sure to call FacebookSdk.sdkInitialize() first.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3113)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3249)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:81)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1940)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:209)
        at android.app.ActivityThread.main(ActivityThread.java:7046)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:486)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)
     Caused by: The SDK has not been initialized, make sure to call FacebookSdk.sdkInitialize() first.
        at com.facebook.internal.Validate.sdkInitialized(Validate.java:144)
        at com.facebook.login.LoginManager.<init>(LoginManager.java:80)
        at com.facebook.login.LoginManager.getInstance(LoginManager.java:93)
        at com.roughike.facebooklogin.facebooklogin.FacebookLoginPlugin$FacebookSignInDelegate.<init>(FacebookLoginPlugin.java:109)
        at com.roughike.facebooklogin.facebooklogin.FacebookLoginPlugin.<init>(FacebookLoginPlugin.java:38)
        at com.roughike.facebooklogin.facebooklogin.FacebookLoginPlugin.registerWith(FacebookLoginPlugin.java:42)
        at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:20)
        at br.com.tappsbeer.tapps_beer.MainActivity.onCreate(MainActivity.kt:11)
        at android.app.Activity.performCreate(Activity.java:7658)
        at android.app.Activity.performCreate(Activity.java:7647)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1295)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3088)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3249) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:81) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1940) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:209) 
        at android.app.ActivityThread.main(ActivityThread.java:7046) 

flutter clean isn't solving. Any ideas?

**Comment by matanshukry** [comment]
Same error here, clean doesn't work either. This issue needs to be reopened.

**Comment by alfredoqt** [comment]
Has anyone been able to solve this? flutter clean does not work for me either.

**Comment by nikhil-concetto** [comment]
You should be write  bellow code in MainActivity.kt

 super.onCreate(savedInstanceState)
        FacebookSdk.setApplicationId(getString(R.string.facebook_app_id))
        FacebookSdk.sdkInitialize(getApplicationContext());

**Comment by RIddhi8701** [comment]
Please refer this link
[https://pub.dev/packages/flutter_facebook_login](url)

**Comment by davydany** [comment]
This is the solution: https://github.com/roughike/flutter_facebook_login/issues/36
